// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFi3s1qELekHm5Pveaaa_Cb197rHTsJQ8',
    appId: '1:173169555526:web:79b6d87fa4778123ab7247',
    messagingSenderId: '173169555526',
    projectId: 'siteyonetimi-4ae4a',
    authDomain: 'siteyonetimi-4ae4a.firebaseapp.com',
    storageBucket: 'siteyonetimi-4ae4a.firebasestorage.app',
    measurementId: 'G-RRYPENEQ0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLf4rsr-lJZNrBT0XJyWJcrjz4EyGabn0',
    appId: '1:173169555526:android:b02c863b6674f12cab7247',
    messagingSenderId: '173169555526',
    projectId: 'siteyonetimi-4ae4a',
    storageBucket: 'siteyonetimi-4ae4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3LvpSVPR9l4gq1DrutMSnlwrgdi9u5sk',
    appId: '1:173169555526:ios:35c4e0c7a75410a4ab7247',
    messagingSenderId: '173169555526',
    projectId: 'siteyonetimi-4ae4a',
    storageBucket: 'siteyonetimi-4ae4a.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3LvpSVPR9l4gq1DrutMSnlwrgdi9u5sk',
    appId: '1:173169555526:ios:35c4e0c7a75410a4ab7247',
    messagingSenderId: '173169555526',
    projectId: 'siteyonetimi-4ae4a',
    storageBucket: 'siteyonetimi-4ae4a.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFi3s1qELekHm5Pveaaa_Cb197rHTsJQ8',
    appId: '1:173169555526:web:a95c192db6ba862cab7247',
    messagingSenderId: '173169555526',
    projectId: 'siteyonetimi-4ae4a',
    authDomain: 'siteyonetimi-4ae4a.firebaseapp.com',
    storageBucket: 'siteyonetimi-4ae4a.firebasestorage.app',
    measurementId: 'G-N9VKD9FDRE',
  );
}
